### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by questionpython** [adtac/captcha-solve#2]
hello,
i also have Tor on my Ubuntu System.

$ python2 main.py
------------
```
Traceback (most recent call last):
  File "main.py", line 126, in <module>
    br.retrieve("https://pizzaonline.dominos.co.in/slot-machine/captcha.php", "temp.jpg");
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_opener.py", line 254, in retrieve
    fp = self.open(req)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 254, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 310, in _mech_open
    raise response
mechanize._response.httperror_seek_wrapper: HTTP Error 404: Not Found
```
how fix?

**Comment by adtac** [comment]
Uhh, I'm sorry, but they removed this feature a long time ago. You can no longer get pizzas for free this way :(

Closing this issue. I'm not even sure if I should even have this repo open.
